version: 2
env_files:
  github_token: ~/.config/git/brightpuddle_pat
before:
  hooks:
    - rm -rf dist
    - go test ./...
builds:
  - id: rep-monitor
    binary: rep-monitor
    targets:
      - windows_amd64_v1
      - linux_amd64_v1
      - darwin_arm64
archives:
  - id: rep-monitor
    format: zip
    files:
      - README.md
      - LICENSE
